# Generated by Django 2.2 on 2021-01-08 03:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.SmallIntegerField(choices=[(0, '开发'), (1, '运营'), (2, '设计')], verbose_name='职位类型')),
                ('job_name', models.CharField(max_length=200, verbose_name='职位名称')),
                ('job_city', models.SmallIntegerField(choices=[(0, '北京'), (1, '上海'), (2, '深圳')], verbose_name='职位类型')),
                ('job_responsibilty', models.TextField(max_length=1024, verbose_name='职位指责')),
                ('job_requirement', models.TextField(max_length=1024, verbose_name='职位要求')),
                ('create_date', models.DateTimeField(verbose_name='创建日期')),
                ('modified_data', models.DateTimeField(verbose_name='修改日期')),
                ('create', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
        ),
    ]
